name: GJS
on:
  pull_request:
  push:

jobs:
  linux:
    strategy:
      matrix:
        node-version: [ 18.x ]
        deno-version: [ vx.x.x ]
        os:
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: sudo apt-get update
      - name: Install Gjs, Gtk and more...
        run: sudo apt-get --yes install gjs libgda-5.0-dev libgirepository1.0-dev libgtk-4-dev libsoup-3.0-dev libwebkit2gtk-4.0-dev libadwaita-1-dev
      - name: Install meson
        run: sudo apt-get --yes install meson
      - name: Install NPM dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test